// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  int    `json:"UserId"`
}

type NewUser struct {
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	Email       string `json:"email"`
	FirstName   string `json:"firstName"`
	LastName    string `json:"lastName"`
	Description string `json:"description"`
}

type NewsPost struct {
	ID      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type Post struct {
	ID      int    `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	UserID  int    `json:"userId"`
	User    *User  `json:"user"`
}

type User struct {
	ID          int     `json:"id"`
	UserName    string  `json:"userName"`
	Password    string  `json:"password"`
	Email       string  `json:"email"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Description string  `json:"description"`
	UUID        string  `json:"uuid"`
	Posts       []*Post `json:"posts"`
	Friends     []*User `json:"friends" gorm:"many2many:friendships;association_jointable_foreignkey:friend_id"`
}
